export default {
	// brands
	'bandcamp' : {displayName: 'Bandcamp'},
	'behance-square' : {displayName: 'Behance'},
	'deviantart' : {displayName: 'DeviantArt'},
	'digg' : {displayName: 'Digg'},
	'etsy' : {displayName: 'Etsy'},
	'facebook-official': {displayName: 'Facebook'},
	'foursquare' : {displayName: 'Foursquare'},
	'github' : {displayName: 'Github'},
	'google-plus-circle' : {displayName: 'Google+'},
	'hacker-news' : {displayName: 'Hacker News'},
	'imdb' : {displayName: 'imdb'},
	'instagram' : {displayName: 'Instagram'},
	'linkedin-square' : {displayName: 'LinkedIn'},
	'medium' : {displayName: 'Medium'},
	'pinterest-square' : {displayName: 'Pinterest'},
	'reddit-square' : {displayName: 'Reddit'},
	'skype' : {displayName: 'Skype'},
	'snapchat-square' : {displayName: 'Snapchat'},
	'soundcloud' : {displayName: 'SoundCloud'},
	'stack-exchange' : {displayName: 'Stack Exchange'},
	'stack-overflow' : {displayName: 'Stack Overflow'},
	'steam-square' : {displayName: 'Steam Square'},
	'tumblr-square' : {displayName: 'Tumblr'},
	'twitch' : {displayName: 'Twitch'},
	'twitter' : {displayName: ''},
	'vimeo-square' : {displayName: 'Vimeo'},
	'wechat' : {displayName: 'WeChat'},
	'whatsapp' : {displayName: 'WhatsApp'},
	'wordpress' : {displayName: 'WordPress'},
	'y-combinator-square' : {displayName: 'Y Combinator'},
	'youtube-square' : {displayName: 'Youtube'},

	// generics
	'envelope-square' : {displayName: 'Email'},
	'phone-square' : {displayName: 'Phone'},
	'external-link-square' : {displayName: 'Website'},
	'mobile-phone' : {displayName: 'Mobile Phone'},
	'graduation-cap' : {displayName: 'Education'},
	'university': {displayName: 'Institution'},
	'user-circle' : {displayName: 'Job Title'},
	'rss-square' : {displayName: 'RSS'},
	'podcast' : {displayName: 'Podcast'}
};
