export default {
	// brands
	'bandcamp' : {displayName: 'Bandcamp', color: '#586e75'},
	'behance-square' : {displayName: 'Behance', color: '#1769ff'},
	'deviantart' : {displayName: 'DeviantArt', color: '#05cc47'},
	'digg' : {displayName: 'Digg', color: '#000000', scale: 0.8},
	'etsy' : {displayName: 'Etsy', color: '#F56400'},
	'facebook-official': {displayName: 'Facebook', color: '#3b5998'},
	'foursquare' : {displayName: 'Foursquare', color: '#2d5be3', scale: 1.1},
	'github' : {displayName: 'Github', color: '#24292e'},
	'google-plus-circle' : {displayName: 'Google+', color: '#dd4b39'},
	'hacker-news' : {displayName: 'Hacker News', color: '#24292e'},
	'imdb' : {displayName: 'imdb', color: '#f5de50', scale: 0.95},
	'instagram' : {displayName: 'Instagram', color: '#125688'},
	'linkedin-square' : {displayName: 'LinkedIn', color: '#007bb5'},
	'medium' : {displayName: 'Medium', color: '#000000', scale: 0.9},
	'pinterest-square' : {displayName: 'Pinterest', color: '#cb2027'},
	'reddit-square' : {displayName: 'Reddit', color: '#cee3f8'},
	'skype' : {displayName: 'Skype', color: '#00aff0'},
	'snapchat-square' : {displayName: 'Snapchat', color: '#fffc00'},
	'soundcloud' : {displayName: 'SoundCloud', color: '#ff5500', scale: 0.7},
	'stack-exchange' : {displayName: 'Stack Exchange'},
	'stack-overflow' : {displayName: 'Stack Overflow', color: '#FF9900'},
	'steam-square' : {displayName: 'Steam', color: '#171a21'},
	'tumblr-square' : {displayName: 'Tumblr', color: '#32506d'},
	'twitch' : {displayName: 'Twitch', color: '#6441a4'},
	'twitter' : {displayName: 'Twitter', color: '#55acee'},
	'vimeo-square' : {displayName: 'Vimeo', color: '#aad450'},
	'wechat' : {displayName: 'WeChat'},
	'whatsapp' : {displayName: 'WhatsApp', color: '#4dc247'},
	'wordpress' : {displayName: 'WordPress', color: '#4f748e'},
	'y-combinator-square' : {displayName: 'Y Combinator', color: '#FF6600'},
	'youtube-square' : {displayName: 'Youtube', color: '#bb0000'},

	// generics
	'envelope-square' : {displayName: 'Email', color: '#1AD6FD'},
	'phone-square' : {displayName: 'Phone', color: '#007AFF'},
	'external-link-square' : {displayName: 'Website'},
	'mobile-phone' : {displayName: 'Mobile Phone', color: '#000000'},
	'graduation-cap' : {displayName: 'Education', color: '#222222', scale: 0.8},
	'university': {displayName: 'Institution', scale: 0.8},
	'user-circle' : {displayName: 'Job Title'},
	'rss-square' : {displayName: 'RSS', color: '#ff6600'},
	'podcast' : {displayName: 'Podcast'}
};
